micronaut:
  application:
    name: aquarium-feeder
    
  server:
    port: 8888
    
  router:
    static-resources:
      default:
        mapping: "/**"
        paths: ["classpath:static"]
    
endpoints:
  all:
    enabled: true
    sensitive: false
  stop:
    enabled: true

cron.def.property: 0*****
