micronaut:
  application:
    name: aquarium-feeder
    
  server:
    port: 8888
    
  router:
    static-resources:
      default:
        mapping: "/**"
        paths: ["file:///home/pi/feeder-gui/static"]
      camera:
        mapping: "/camera/**"
        paths: ["file:///home/pi/camera/"]
    
endpoints:
  all:
    enabled: true
    sensitive: false
  stop:
    enabled: true

cron.def.property: 0*****
